name: App Docker
env:
  GH_TOKEN: ${{secrets.GH_TOKEN}}
on:
  push:
    branches: master

jobs:

  build:

    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    
    - name: Build the Docker tag image LeafApp
      run: docker build . --file app.Dockerfile --tag sultankm/leafapp:${GITHUB_SHA}
    - name: Push LeafApp to DockerHub tag
      run: docker push sultankm/leafapp:${GITHUB_SHA}
    
    - name: Build the Docker latest image Flow.Web
      run: docker build . --file app.Dockerfile --tag sultankm/leafapp:latest
    - name: Push LeafApp to DockerHub latest
      run: docker push sultankm/leafapp:latest
